on:
    push:
      branches:
        - master
      tags: '*'
    pull_request:

language: julia
julia:
  - nightly
  - 1.11
  - 1.10

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs2/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs2/ docs2/make.jl
      after_success: skip

codecov: true
coveralls: true
